import Dish1 from './dish1.jpg';
import Dish2 from './dish2.jpg';
import Dish3 from './dish3.jpg';
import Dish4 from './dish4.jpg';

export default function menuPane(main){
    const menu = document.createElement('div');
    menu.classList.add('menu');
    const food1 = document.createElement('div');
    const food2 = document.createElement('div');
    const food3 = document.createElement('div');
    const food4 = document.createElement('div');
    const dish1 = new Image();
    dish1.src = Dish1;
    const dish2 = new Image();
    dish2.src = Dish2;
    const dish3 = new Image();
    dish3.src = Dish3;
    const dish4 = new Image();
    dish4.src = Dish4;
    const text1 = document.createElement('p');
    const text2 = document.createElement('p');
    const text3 = document.createElement('p');
    const text4 = document.createElement('p');
    const heading1 = document.createElement('h3');
    const heading2 = document.createElement('h3');
    const heading3 = document.createElement('h3');
    const heading4 = document.createElement('h3');
    heading1.textContent = "Lorem Ipsum";
    heading2.textContent = "Lorem Ipsum";
    heading3.textContent = "Lorem Ipsum";
    heading4.textContent = "Lorem Ipsum";
    text1.textContent = "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.";
    text2.textContent = "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.";
    text3.textContent = "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.";
    text4.textContent = "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.";
    food1.appendChild(dish1);
    food1.appendChild(heading1);
    food1.appendChild(text1);
    food2.appendChild(dish2);
    food2.appendChild(heading2);
    food2.appendChild(text2);
    food3.appendChild(dish3);
    food3.appendChild(heading3);
    food3.appendChild(text3);
    food4.appendChild(dish4);
    food4.appendChild(heading4);
    food4.appendChild(text4);
    menu.appendChild(food1);
    menu.appendChild(food2);
    menu.appendChild(food3);
    menu.appendChild(food4);
    main.appendChild(menu);
}